# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmWebSite', '0002_dmwebsiteuseronlyemails'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmWebsiteContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_message', models.CharField(max_length=600)),
            ],
        ),
    ]
