# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-31 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmWebSite', '0003_dmwebsitecontactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmwebsitecontactus',
            name='sts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmwebsiteuser',
            name='sts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmwebsiteuseronlyemails',
            name='sts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
