# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-31 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmWebSite', '0004_auto_20180731_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmWebsiteSubmitProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=50)),
                ('user_institution', models.CharField(max_length=100)),
                ('user_domain', models.CharField(max_length=200)),
                ('user_project_title', models.CharField(max_length=200)),
                ('user_project_description', models.CharField(max_length=600)),
                ('sts', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
